source/repos/Records/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Records.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

source/repos/Records/Controllers/LoginController.cs
using Records.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Records.Controllers
{
    public class LoginController : Controller
    {
        ActionMonitor a = new ActionMonitor();
        ActionModel m = new ActionModel();
        // GET: Login
        UserModel u = new UserModel();
        User t = new User();

        public ActionResult Home()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Logout");
            }
            return View();
        }
        public ActionResult Login()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Login(UserValidation user)

        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            if (user.Password.TrimEnd().Equals(user.rPassword.TrimEnd()))
            {
                t.Id = user.Id;
                t.Name = user.Name;
                t.EmailId = user.Email;
                t.Password = u.Enc(user.Password);
               TempData["a"]= Convert.ToString(user.Name);
                TempData["b"] = Convert.ToString(user.Email);
                u.Add(t);
                u.Save();
                string te = Convert.ToString(TempData["a"]);
                a.Name = te;
                a.ActionPerformed = "Create an Account";
                a.During = DateTime.Now;
                m.Add(a);
                m.Save();
                return RedirectToAction("Register");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public ActionResult Userlist()
        {
            var r = u.FindAllUsers();
            return View(r);
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterValidation registerValidation)

        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData["a"]= Convert.ToString(registerValidation.Name);
            string temp =Convert.ToString( TempData["a"]);
            var data = u.GetUserByName(registerValidation.Name);
            var encpass = u.Dec(data.Password.TrimEnd());
            bool userName = data.Name.TrimEnd().Equals(registerValidation.Name);
            bool userEmail = data.EmailId.TrimEnd().Equals(registerValidation.Email);
            bool userPassword = encpass.TrimEnd().Equals(registerValidation.Password);
            if (userName && userEmail && userPassword)
            {
                var ticket = new FormsAuthenticationTicket(registerValidation.Name,true,3000);
                string encrypt = FormsAuthentication.Encrypt(ticket);
                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypt);
                cookie.Expires = DateTime.Now.AddHours(3000);
                cookie.HttpOnly=true;
                Response.Cookies.Add(cookie);
                a.Name = temp;
                a.ActionPerformed = "Login";
                a.During = DateTime.Now;
                m.Add(a);
                m.Save();
                if (registerValidation.Name.Equals("Admin"))
                    return RedirectToAction("AdminPage");
                else
                    return RedirectToAction("UserPage");
            }
            return View("Error");
        }
        public ActionResult Error()
        {
            return View();
        }
        public ActionResult Delete(int id)
        {
            var data = u.GetUser(id);
            u.Delete(data);
            u.Save();
            a.Name = data.Name;
            a.ActionPerformed = "Account Deletion";
            a.During = DateTime.Now;
            m.Add(a);
            m.Save();
            return RedirectToAction("Userlist");
        }
        [Authorize(Roles="Admin")]
        public ActionResult AdminPage()
        {
            return View();
        }
        [Authorize]
        public ActionResult UserPage()
        {
            return View();
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            a.Name = User.Identity.Name;
            a.ActionPerformed = "Logout";
            a.During = DateTime.Now;
            m.Add(a);
            m.Save();
            return RedirectToAction("Home");
        }
    }
}

source/repos/Records/Controllers/PrimaryController.cs
using GoogleMaps.LocationServices;
using Records.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Records.Controllers
{
    [Authorize]
    public class PrimaryController : Controller
    {
        // GET: Primary
        ActionMonitor a = new ActionMonitor();
        ActionModel k = new ActionModel();
        Client c = new Client();
        DinnerModel m = new DinnerModel();
       
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(ValidateForm v)
        {
            c.Title = v.Title;
            c.HostedBy = v.HostedBy;
            c.Description = v.Description;
            c.EventDate = v.EventDate;
            c.ContactPhone = v.ContactPhone;
            c.Address = v.Address;
            c.Country = v.Country;
            c.Latitude = v.Latitude;
            c.Longtitude = v.Longtitude;
            m.Add(c);
            m.Save();
            a.Name = Convert.ToString("Admin");
            a.ActionPerformed = "Created a Dinner";
            a.During = DateTime.Now;
            k.Add(a);
            k.Save();
            TempData["InsertMsg"] = "<script>alert('Data inserted successfully');</script>";

            return RedirectToAction("Display");
        }
       
        public ActionResult Display()
        {
            var data= m.FindAllDinners();
            return View(data);
        }
        public ActionResult DisplayUser()
        {
            var data = m.FindAllDinners();
            return View(data);
        }
        public ActionResult Edit( int Id)
        {
            var data = (ValidateForm) m.GetDinner(Id);
            //int r = data.DinnerId;
            return View(data);
           
        }
        [HttpPost]
        public ActionResult Edit(ValidateForm v)

        { Client c =m.GetDinner(v.DinnerId);
            c.DinnerID = v.DinnerId;
            c.Title = v.Title;
            c.HostedBy = v.HostedBy;
            c.Description = v.Description;
            c.EventDate = v.EventDate;
            c.ContactPhone = v.ContactPhone;
            c.Address = v.Address;
            c.Country = v.Country;
            
            
          c.Latitude = v.Latitude;
            c.Longtitude = v.Longtitude;
            // m.Add(c);
            m.Save();
            Response.Write("<script>alert('Data Updated successfully');</script>");
            return RedirectToAction("Display");
        }
       
        public ActionResult Details(int id)
        {
            var data =(ValidateForm) m.GetDinner(id);
            return View(data);
        }
        // GET: Primary/Details/5
        public ActionResult Delete(int id)
        {
            Client c = m.GetDinner(id);
            m.Delete(c);
            m.Save();
            TempData["DeleteMsg"] = "<script>alert('Data deleted successfully');</script>";
            return RedirectToAction("Display");
        }
        public ActionResult AllMaps()
        {
            return View();
        }
        public JsonResult GetMapMarker()
        {
            var ListOfAddress =m.FindAllDinners().ToList();
            return Json(ListOfAddress, JsonRequestBehavior.AllowGet);
        }
    public ActionResult temp()
        {
            return View();
        }

    }
}

source/repos/Records/Views/Login/AdminPage.cshtml
@{
    ViewBag.Title = "AdminPage";
}
@{
    TempData.Keep("a");
}
<p id="a"><h2>AdminPage</h2></p>
<style>
    #a {
        background-color: yellow;
        text-align: center;
    }

    #b {
        background-color: darkorange;
        text-align: center;
    }
</style>
<div>

    <p id="b"><h3> Welcome @TempData["a"]</h3></p>
</div>
<div>

    <table border="1" width="100%" height="50%">
        <tr>
            <th id="a">
                @Html.ActionLink("User Details", "UserList")
            </th>
            <th id="b">
                @Html.ActionLink("Dinner Details", "Display", "Primary")
            </th>
            <th id="a">
                @Html.ActionLink("History", "Show", "History")
            </th>
            <th id="b">
                @Html.ActionLink("Booking Details", "BookersList", "History")
            </th>
            <th id="a">
                @Html.ActionLink("Map View", "AllMaps", "Primary")
            </th>
        </tr>


    </table>

</div>
<div>
    <div>
        <p> User details displays the total no of users</p>
    </div>
</div>

source/repos/Records/Views/Login/Home.cshtml
@{
    ViewBag.Title = "Home";
}

    <style type="text/css">
         .CLA{
            background-image: url('~/Content/NewFolder1/homepage.jpg');
            margin: 0;
        }
    </style>


    <div>
        <header><button class="alert-success">  @Html.ActionLink("Login", "Register")</button> </header>
    </div>

source/repos/Records/Views/Login/Login.cshtml
@model Records.Models.UserValidation

@{
    ViewBag.Title = "Login";
}

<h2>Register</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>UserValidation</h4>
    <hr />
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.rPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.rPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Register" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back ", "Register")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/repos/Records/Views/Login/Register.cshtml
@model Records.Models.RegisterValidation

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>
@Html.ActionLink("Create Account","Login")
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterValidation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Log In" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

source/repos/Records/Views/Login/UserPage.cshtml
@{
    ViewBag.Title = "UserPage";
}

<h2>UserPage</h2>

<div>

    <h3> Welcome @TempData["a"]</h3>
    @{
        TempData.Keep("a");
        var data = TempData["a"];
        TempData.Keep("a");
    }
</div>

<div>
    <table width="100%" cellspacing="4">



        <thead>
            @Html.ActionLink("Dinner Details", "DisplayUser", "Primary")
        </thead>
    </table>
</div>
<a href="@Url.Action("DisplayBook","History", new { Name=data})"> Booking Details</a>

source/repos/Records/Views/Login/Userlist.cshtml
@model IEnumerable<Records.Models.User>

@{
    ViewBag.Title = "Userlist";
}
<style>
    div{
        background-color:aqua;
    }
</style>
<h2>Userlist</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
           
           
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
@Html.ActionLink("Back ","AdminPage")